[package]
name = "parser"
version = "0.0.1"
edition = "2021"

[lib]
bench = false

[dependencies]
nom = "7.1.2"
nom_locate = "4.1.0"

[dev-dependencies]
criterion = "0.4.0"
iai = "0.1.1"
indoc = "1.0.3"


[[bench]]
name = "http_parser"
harness = false
